### ISSUE TITLE
Update: schema 4.82 / sysmon 14

### ISSUE THREAD

**Issue by LasseKrache** [darkoperator/vscode-sysmon#8]
Just stumbled across your github page as I am searching for a tool writing/editing my sysmon configuration files.
I will install your extension (thank you very much for it!), but would kindly ask, if there are any plans to update your tool to the new schema (4.82?) or to the sysmon version 14?

Kind regards,
Lasse

**Comment by darkoperator** [comment]
Estension in vscode store has the latest update covering it. I need to push the files to github but have been busy

**Comment by LasseKrache** [comment]
Thank you very much for your quick response and your work!
Un buen fin de semana,
Lasse
